Refactor endpoints - issue #31
Clariteia/discovery pull request #40
Opened 2021-08-05 06:49 UTC by albamig

Resolves #31

2021-08-05 14:40 UTC, albamig commented
Refactoring the endpoints wasn't so easy since that logic goes throughtout the whole application. Thus, I've used this task to simplify the whole service and get rid of configuration.

2021-08-06 08:31 UTC, garciparedes requested changes
Hi @albamig, could you add more tests to increase the coverage?

2021-08-06 08:59 UTC, albamig commented
> Hi @albamig, could you add more tests to increase the coverage?

I reverted to previous `pragma: no cover`. We should work on this in the future.

2021-08-06 10:14 UTC, vladyslav-fenchak approved these changes

2021-08-09 07:07 UTC, garciparedes commented on minos/api_gateway/discovery/database/client.py
> +            raise exc
As we are re-raising this exception without including any new logic, we should remove this `try-except` statement for simplicity sake

2021-08-09 07:11 UTC, garciparedes requested changes
Hi @albamig, good refactoring! Could you review the comments I left to you?

2021-08-09 07:11 UTC, garciparedes commented on minos/api_gateway/discovery/handlers.py
> +    redis_client.set_data(input_json["name"], input_json)
Why not to set the `MinosRedisClient` as a `web.Applicantion` configuration entry, instead of recreating it each time a request comes?

2021-08-09 07:21 UTC, albamig commented
> Hi @albamig, good refactoring! Could you review the comments I left to you?

Sorry @garciparedes, I had not seen them :sweat_smile: 
All what you've said I agree with it, but I'd rather deal with all the database connection stuff in other issues. Here and in #46 I think it's better to just refactor the endpoints and have a proper structure.

2021-08-09 07:29 UTC, garciparedes commented
> > Hi @albamig, good refactoring! Could you review the comments I left to you?
> 
> Sorry @garciparedes, I had not seen them 😅.
> 
> All what you've said I agree with it, but I'd rather deal with all the database connection stuff in other issues. Here and in #46 I think it's better to just refactor the endpoints and have a proper structure.

Okay, so I'll copy my comment on that PR and proceed to accept this one. 😉

2021-08-09 07:31 UTC, garciparedes commented on minos/api_gateway/discovery/handlers.py
> +    redis_client.set_data(input_json["name"], input_json)
This question will be resolved by https://github.com/Clariteia/discovery/pull/46/files#r684969388

2021-08-09 07:31 UTC, garciparedes approved these changes

2021-08-09 07:34 UTC, albamig commented
> > > Hi @albamig, good refactoring! Could you review the comments I left to you?
> > 
> > 
> > Sorry @garciparedes, I had not seen them sweat_smile.
> > All what you've said I agree with it, but I'd rather deal with all the database connection stuff in other issues. Here and in #46 I think it's better to just refactor the endpoints and have a proper structure.
> 
> Okay, so I'll copy my comment on that PR and proceed to accept this one.



Great! Thanks @garciparedes 
Probably issue #43 is the right spot for it.

2021-08-10 09:51 UTC, merged